server:
  port: 18885  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local}
    loadbalancer:
      nacos:
        enabled: true
      ribbon:
        enabled: false
  application:
    name: ts-cancel-service

swagger:
  controllerPackage: cancel.controller
